[[insns-fcvt.bf16.s, Convert FP32 to BF16]]
=== FCVT.BF16.S

Synopsis::
Convert FP32 value to a BF16 value

Mnemonic::
FCVT.BF16.S rd, rs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '00100', attr: ['BF16.S']},
{bits: 2, name: '10', attr: ['H']},
{bits: 5, name: '01000', attr: 'FVCT'},
]}
....
// S.B16 = 001,S=00

[NOTE]
====
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point convert instructions, the coding is necessarily different as all of the _fmt_ encodings have been assigned to other floating-point formats.

The "S.B16" field is intended to signify that the source is FP32 and the "H" of the destination is
to be interpreted as BF16. We need to see what encodings are currently used here, and if there is any
room for such encodings.
====

Description:: 
Narrowing convert FP32 value to a BF16 value. Round according to the RM field. 

This new floating-point-to-floating-point conversion instruction is defined analogously to the other floating-point-to-floating-point conversion instructions.

The result is NaN-boxed by writing all of the most significant `FLEN`-32 bits with 1s.

Exceptions:  Overflow, Underflow, Inexact, Invalid

// [NOTE]
// ====
// It might seem odd that a conversion to a smaller format with the same exponent can underflow. However, the IEEE-754
// definition of underflow requires a loss of accuracy and the a tiny result. An FP32 subnormal number is already tiny.
// If the conversion loses any significant bits, it is inexact and an underflow occurs.
// ====

// Operation::
// --
// --

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zFBFMIN>>
| v0.0.1
| Initial
|===


