[[insns-fcvt.s.bf16, Convert BF16 to FP32]]
=== FCVT.S.BF16

Synopsis::
Convert BF16 value to an FP32 value

Mnemonic::
FCVT.S.BF16 rd, rs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '00110', attr: ['BF16']},
{bits: 2, name: '00', attr: ['S']},
{bits: 5, name: '01000', attr: 'FVCT'},
]}
....

[NOTE]
====
.Encoding
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point
convert instructions, a new encoding is
used in bits 24:20 to indicate that the source is BF16.
====


Description:: 
Converts a BF16 value to an FP32 value. The conversion is exact.

This new floating-point-to-floating-point conversion instruction is defined analogously to the
pre-existing floating-point-to-floating-point conversion instructions.

If the input is normal or infinity, the BF16 encoded value is shifted to the left by 16 places and the
least significant 16 bits are written with 0s.
If the input is a NaN, the canonical NaN is returned. Furthermore, if the input is a signalling NaN,
the invalid flag is rasied. 


The result is NaN-boxed by writing the most significant `FLEN`-32 bits with 1s.

Exceptions: Invalid

// Operation::
// --
// --

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zfbfmin>>
| v0.0.1
| Initial
// | <<zfbfinxmin>>
// | v0.0.1
// | Initial
|===


