[[insns-fcvt.bf16.s, Convert FP32 to BF16]]
=== FCVT.BF16.S

Synopsis::
Convert FP32 value to a BF16 value

Mnemonic::
FCVT.BF16.S rd, rs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '01000', attr: ['BF16.S']},
{bits: 2, name: '10', attr: ['H']},
{bits: 5, name: '01000', attr: 'FCVT'},
]}
....
// S.B16 = 001,S=00


[NOTE]
====
.Encoding
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point convert instructions,
a new encoding is used in bits 24:20.

`BF16.S` and `H` are used to signify that the source is FP32 and the destination is BF16.
====


Description:: 
Narrowing convert FP32 value to a BF16 value. Round according to the RM field. 

This new floating-point-to-floating-point conversion instruction is defined analogously to the
pre-existing floating-point-to-floating-point conversion instructions.

The result is NaN-boxed by writing all of the most significant `FLEN`-16 bits with 1s.

Exceptions:  Overflow, Underflow, Inexact, Invalid

// Operation::
// --
// --

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zfbfmin>>
| v0.0.1
| Initial
// | <<zfbfinxmin>>
// | v0.0.1
// | Initial
|===


