[[insns-fcvt.s.bf16, Convert BF16 to FP32]]
=== FCVT.S.BF16

Synopsis::
Convert BF16 value to an FP32 value

Mnemonic::
FCVT.S.BF16 rd, rs1

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010011', attr: ['OP-FP']},
{bits: 5, name: 'rd'},
{bits: 3, name: 'rm'},
{bits: 5, name: 'rs1'},
{bits: 5, name: '00110', attr: ['BF16']},
{bits: 2, name: '00', attr: ['S']},
{bits: 5, name: '01000', attr: 'FVCT'},
]}
....

[Note]
.Encoding
While the mnemonic of this instruction is consistent with that of the other RISC-V floating-point convert instructions, the coding is necessarily different as all of the _fmt_ encodings have been assigned to other floating-point formats.

.Encoding
The "H.B16" field is intended to signify that the source is 16 bits to be interpreted as BF16.
We need to see what encodings are currently used here, and if there is any room for such encodings.

Description:: 
Convert BF16 value to an FP32 value. The conversion is exact.

This new floating-point-to-floating-point conversion instruction is defined analogously to the other floating-point-to-floating-point conversion instructions.

The BF16 encoded value is shifted to the left by 16 places and the least significant 16 bits are
written with 0s. The result is NaN-boxed by writing the most significant `FLEN`-32 bits with 1s.

Exceptions: Invalid

// Operation::
// --
// --

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zFBFMIN>>
| v0.0.1
| Initial
|===


