[[insns-vfncvtbf16.f.f.w, Vector convert FP32 to BF16]]
=== vfncvtbf16.f.f.w

Synopsis::
Vector convert FP32 to BF16

Mnemonic::
vfncvtbf16.f.f.w vd, vs2, vm

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPFVV'},
{bits: 5, name: '11101'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'VFUNARY0'},
]}
....

Description:: 
Convert FP32 to BF16. Round according to the RM field. 

This new floating-point-to-floating-point conversion instruction is defined analogously to the other floating-point-to-floating-point conversion instructions.
This instruction is similar to vfncvt.f.f.w - Convert double-width float to single-width float. However, it is only defined for SEW=16.
Any attempt to execute this instruction with an SEW other than SEW=16 will result in an illegal
instruction exception.

Exceptions: Overflow, Inexact, Invalid

Operation::
--

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvfbfmin>>
| v0.0.1
| Initial
|===


