[[insns-vfwcvtbf16.f.f.v, Vector convert BF16 to FP32]]
=== vfwcvtbf16.f.f.v

Synopsis::
Vector convert BF16 to FP32

Mnemonic::
vfwcvtbf16.f.f.v vd, vs2, vm

Encoding::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: 'OP-V'},
{bits: 5, name: 'vd'},
{bits: 3, name: 'OPFVV'},
{bits: 5, name: '01101'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 'VFUNARY0'},
]}
....


Description:: 
Convert BF16 to FP32. The conversion is exact.

This new floating-point-to-floating-point conversion instruction is defined analogously to the other floating-point-to-floating-point conversion instructions.
This instruction is similar to vfwcvt.f.f.v - Convert single-width float to double-width float. However, it is only defined for SEW=16.

Any attempt to execute this instruction with an SEW other than 16 will result in an illegal
instruction exception.

Exceptions: Invalid


Operation::
[source,sail]
--

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvfbfmin>>
| v0.0.1
| Initial
|===


