[#insns-vfwmaccbf16, reftext="Vector BF16 widening multiply-accumulate"]
=== vfwmaccbf16 

Synopsis::
Vector BF16 widening multiply-accumulate

Mnemonic::
vfwmaccbf16.vv vd, vs1, vs2, vm +
vfwmaccbf16.vf vd, rs1, vs2, vm +

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '001', attr:['OPFVV']},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111011, attr:['vfwmaccbf16']},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '101', attr:['OPFVF']},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111011, attr:['vfwmaccbf16']},
]}
....
// funct6=111011
Reserved Encodings::
* `SEW` is any value other than 16 

Arguments::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|Register
|Direction
|EEW
|Definition

| Vd  | input  | 32  | FP32 Accumulate
| Vs1 | input  | 16  | BF16 Source
| Vs2 | input  | 16  | BF16 Source
| Vd  | output | 32  | FP32 Result
|===

Description:: 
This instruction perfoms a wideing fused multiply-accumulate operation, when each pair of BF16 values
are multiplied and their unrounded product is added to the corresponding FP32 accumulate value. The
sum is rounded to FP32.
In the vector-vector version, the BF16 elements are read from `vs1` and `vs2` and
FP32 accumulate value is read from `vd`.
The vector-scalar version is similar, but instead of reading elements from `vs1`, a scalar BF16 value is
read from the FPU register `rs1`.  
The FP32 result is written to the destination register `rd`.

Exceptions: Overflow, Underflow, Inexact, Invalid

Operation::
--
This instruction is equivelent to widening each of the BF16 inputs to FP32 and then performing an FMACC.

Thus vfwmaccbf16.vv is equivalent to the following instruction sequence:

vfwcvtbf16.f.f.v T1, vs1, vm +
vfwcvtbf16.f.f.v T2, vs2, vm +
vfmacc.vv vd, T1, T2, vm

Likewise, vfwmaccbf16.vs is equivalent to the following instruction sequence:

fcvt.s.bf16 T1, rs1 +
vfwcvtbf16.f.f.v T2, vs2, vm +
vfmacc.vv vd, T1, T2, vm

--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvfbfwma>>
| v0.0.1
| Initial
|===


