[#insns-vfwmaccbf16, reftext="Vector BF16 widening multiply-accumulate"]
=== vfwmaccbf16 

Synopsis::
Vector BF16 widening multiply-accumulate

Mnemonic::
vfwmaccbf16.vv vd, vs2, vs1, vm +
vfwmaccbf16.vf vd, vs2, rs1, vm +

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:[`OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '010', attr:['OPMVV']},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111011, attr:['vfwmaccbf16']},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:[`OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '110', attr:['OPMVX']},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111011, attr:['vfwmaccbf16']},
]}
....
// funct6=111011
Reserved Encodings::
* `SEW` is any value other than 16 

Arguments::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|Register
|Direction
|EEW
|Definition

| Vd  | input  | 32  | FP32 Accumulate
| Vs1 | input  | 32  | BF16 Source
| Vs2 | input  | 32  | BF16 Source
| Vd  | output | 16  | BF16 Result
|===

Description:: 
Multiplies BF16 values in `vs1` and `vs2` and adds the product to the FP32 value in `vd`.
The FP32 result is returned with a single rounding based on the mode in the `frm` register.

Exceptions: Overflow, Underflow, Inexact, Invalid

Operation::
--
Each of the BF16 inputs is widened to FP32 and then an FMACC is performed

vfwcvtbf16.f.f.v T1, vs1, vm
vfwcvtbf16.f.f.v T2, vs2, vm
vfmacc.vv vd, T1, T2, vm
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvfbfwma>>
| v0.0.1
| Initial
|===


