[[insns-vfwmulbf16, Vector BF16 widening multiply]]
=== vfwmulbf16

Synopsis::
Vector BF16 widening multiply

Mnemonic::
vfwmulbf16.vv vd, vs2, vs1, vm +
vfwmulbf16.vf vd, vs2, rs1, vm +

Encoding (Vector-Vector)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '010', attr:['OPMVV']},
{bits: 5, name: 'vs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111001, attr:['vfwmulbf']},
]}
....

Encoding (Vector-Scalar)::
[wavedrom, , svg]
....
{reg:[
{bits: 7, name: '1010111', attr:['OP-V']},
{bits: 5, name: 'vd'},
{bits: 3, name: '110', attr:['OPMVX']},
{bits: 5, name: 'rs1'},
{bits: 5, name: 'vs2'},
{bits: 1, name: 'vm'},
{bits: 6, name: 111001, attr:['vfwmulbf']},
]}
....

// funct6=111001
Reserved Encodings::
* `SEW` is any value other than 16 

Arguments::
[%autowidth]
[%header,cols="4,2,2,2"]
|===
|Register
|Direction
|EEW
|Definition

| vs1/rs1 | input  | 32  | BF16 Source
| vs2 | input  | 32  | BF16 Source
| vd  | output | 16  | BF16 Product
|===

Description:: 
Multiplies BF16 values in `vs1` and `vs2`.
The FP32 result is returned with rounding based on the mode in the `frm` register.

Any attempt to execute this instruction with an SEW other than SEW=16 will result in an illegal
instruction exception.

Exceptions: Overflow, Underflow, Inexact, Invalid

Operation::
--
Each of the BF16 inputs is widened to FP32 and multiplied together.

Vector-vector
vfwcvtbf16.f.f.v T1, vs1, vm
vfwcvtbf16.f.f.v T2, vs2, vm
vfmul.vv vd, T1, T2, vm

vector-scalar
get scalar
vfwcvtbf16.f.f.v T1, vs1, vm
vfwcvtbf16.f.f.v T2, vs2, vm
vfmul.vv vd, T1, T2, vm
--

Included in::
[%header,cols="4,2,2"]
|===
|Extension
|Minimum version
|Lifecycle state

| <<zvfbfwma>>
| v0.0.1
| Initial
|===


