//:This is the preamble.

[preamble]
// = Colophon

This document describes the BF16 format and instruction extensions to the 
RISC-V Instruction Set Architecture.

This document is in the link:http://riscv.org/spec-state[Discussion State].
This specification is in the early stages. Comments and proposals
are encouraged.
For more information, see link:http://riscv.org/spec-state[here].

[NOTE]
.Copyright and licensure:
This work is licensed under a
link:http://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License]

[NOTE]
.Document Version Information:
====
//include::git-commit.adoc[]

See link:https://github.com/riscv/riscv-alt-fp[github.com/riscv/riscv-alt-fp]
for more information.
====

[acknowledgments]
== Acknowledgments

Contributors to all versions of the specification (in alphabetical order)
include:
[square]
* GouYue +
* link:mailto:kad@rivosinc.com[Ken Dockser] (Editor) +
* Nick Knight +
* _Your name here_ +

We will be very grateful to the huge number of other people who will
have helped to improve this specification through their comments, reviews,
feedback and questions.
