[[bfloat16_extensions]]
== Extensions

The group of extensions introduced by the BFloat16 Instruction Set
Extension is listed here.

Detection of individual BFloat16 extensions uses the
unified software-based RISC-V discovery method.

[NOTE]
====
At the time of writing, these discovery mechanisms are still a work in
progress.
====

.A note on extension rationale
[NOTE, caption="SH"]
====
BFloat16 instructions are separated into different
functional groups because not all implementations will require all
of the functionality.

====


The BFloat16 extensions depend on the half-precision floating-point extensions (Zfh and Zfhmin), which in turn rely on the single-precision floating-point extension (F).


The Bfloat16 extensions do not add any new load or store instructions, as the FLH and FSH 16-bit load and store instructions introduced by the half-precision extensions work just fine for Bfloat16 values.


This initial set of BFloat16 extensions provide very basic functionality including conversion between BFloat16 and single-precision values for scalar and vector, and widening multiply-add instructions that return a single-precision result.

include::riscv-bfloat16-zfbfmin.adoc[]
include::riscv-bfloat16-zvfbfmin.adoc[]
include::riscv-bfloat16-zvfbfwma.adoc[]
