[[BF16_extensions]]
== Extensions

The group of extensions introduced by the BF16 Instruction Set
Extensions is listed here.

Detection of individual BF16 extensions uses the
unified software-based RISC-V discovery method.

[NOTE]
====
At the time of writing, these discovery mechanisms are still a work in
progress.
====

//.A note on extension rationale
//[NOTE, caption="SH"]
//====
//BF16 instructions are separated into different
//functional groups because not all implementations will require all
//of the functionality.
//====


The BF16 extensions defined in this specification depend on the single-precision floating-point extension
`F`.


//The BF16 extensions do not add any new load, store or move instructions, instead the `Zfbfmin` extension
//includes the `FLH`, `FSH`, `FMV.H.X`, and `FMV.X.H` instructions as defined in the `Zfh` extension.


This initial set of BF16 extensions provide very basic functionality including conversion between BF16 and single-precision values for scalar and vector, and widening multiply-add instructions that return a single-precision result.

include::riscv-bfloat16-zfbfmin.adoc[]
include::riscv-bfloat16-zvfbfmin.adoc[]
include::riscv-bfloat16-zvfbfwma.adoc[]
