[[zfbfmin, Zfbfmin]]
=== `Zfbfmin` - Scalar BF16 Converts

This extension provides the minimal set of instructions needed to enable scalar support
of the BF16 format. It enables BF16 as an interchange format as it provides conversion
between BF16 values and FP32 values. 

This extension includes the `FLH`, `FSH`, `FMV.X.H`, and `FMV.H.X` instructions
that are defined in the `Zfh` spec. That said, this extension does not require
nor depend on the implementation of the `Zfh` or `Zfhmin` extensions.

This extension depends on the single-precision floating-point extension `F`.

[NOTE]
====
While conversion instructions tend to include all supported formats, in these extensions we
only support conversion between BF16 and FP32 as we are targeting a special use case.
These extensions are intended to support the case where BF16 values are used as reduced
precision versions of FP32 values, where use of BF16 provides a two-fold advantage for
storage, bandwidth, and computation. In this use case, the BF16 values are typcially 
multiplied by each other and accumulated into FP32 sums. 
These sums are typcially converted to BF16
and then used as subsequent inputs. The operations on the BF16 values can be performed
on the CPU or a loosly coupled coprocessor.

Subsequent extensions might provide support for native BF16 arithmetic. Such extensions
could add additional conversion
instructions to allow all suported formats to be converted to and from BF16.  
====

[NOTE]
====
BF16 arithmetic operations can be
faithfully emulated by converting the BF16 operands to single-precision, performing the
operation using single-precision arithmetic, and then converting back to BF16. Performing
BF16 fused multiply-addition using this method can produce results that differ by 1-ulp 
on some inputs for the RNE and RMM rounding modes.

Likewise, exact conversions from BF16 to larger precisions can be synthesized by first
converting to FP32 and then converting from FP32 to the target precision. Conversions
from larger precisions coud be synthesized by first converting to FP32 and then
converting from FP32 to BF16. As with the arithmetic instructions described above,
this method of converting values to BF16 can be off by by 1-ulp 
on some inputs for the RNE and RMM rounding modes.
====

[%autowidth]
[%header,cols="2,4"]
|===
|Mnemonic
|Instruction
|FCVT.BF16.S    | <<insns-fcvt.bf16.s>>
|FCVT.S.BF16    | <<insns-fcvt.s.bf16>>
|FLH            | 
|FSH            |
|FMV.H.X        |
|FMV.X.H        |
|===

