//:This is the preamble.

[preamble]
// = Colophon

This document describes the BF16 format and instruction extensions to the 
RISC-V Instruction Set Architecture.

[WARNING]
.This document is in the link:http://riscv.org/spec-state[Frozen] State
====
Change is extremely unlikely. A high threshold will be used, and a change will only occur because of some truly critical issue being identified during the public review cycle. Any other desired or needed changes can be the subject of a follow-on new extension.
====

[NOTE]
.Copyright and licensure:
This work is licensed under a
link:http://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License]

[NOTE]
.Document Version Information:
====
//include::git-commit.adoc[]

See link:https://github.com/riscv/riscv-bfloat16[github.com/riscv/riscv-bfloat16]
for more information.
====

[acknowledgments]
== Acknowledgments

Contributors to all versions of the specification (in alphabetical order)
include:
[square]
* GouYue +
* link:mailto:kdockser@tenstorrent.com[Ken Dockser] (Editor) +
* Kenneth Rovers +
* Nick Knight +
* Nicolas Brunie +

We are grateful to the other people who
have helped to improve this specification through their comments, reviews,
feedback and questions.
